version: '3'
services:


  db:
    image: postgres:10
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=wordpress
      - POSTGRES_USER=artkon
      - POSTGRES_PASSWORD=11112005
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  webserver:
#    depends_on:
#      - wordpress
#    image: nginx:latest
#    container_name: webserver
#    restart: unless-stopped
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#      - ./data/html:/var/www/html
#      - ./logs/nginx:/var/log/nginx
#    links:
#      - wordpress


  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./certbot:/etc/letsencrypt
    links:
      - wordpress

  certbot:
     image: certbot/certbot:latest
     volumes:
       - ./data/html:/var/www/html/:rw
       - ./certbot:/etc/letsencrypt/:rw
     depends_on:
       - webserver
     command: certonly --webroot --webroot-path=/var/www/html --email hichneg@gmail.com --agree-tos --no-eff-email --force-renewal  -d artur.egloo.kz



  wordpress:
    depends_on:
      - db
    image: artkon7/mywordpress:2.0
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=artkon
      - WORDPRESS_DB_PASSWORD=11112005
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./data/html:/var/www/html
      - ./data/html/wp-content:/var/www/html/wp-content
    links:
      - db
    
#  pgadmin:
#    image: dpage/pgadmin4
#    depends_on:
#      - db
#    ports:
#      - "443:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    restart: unless-stopped
